# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ministryofhealth.sharad.com:
  aiimsindia.hospital.sharad.com:
  uhgusa.hospital.sharad.com:
  sbi.insurancecompany.sharad.com:
  uhg.insurancecompany.sharad.com:

networks:
  mcdl:

services:

  ministryofhealth.sharad.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: ministryofhealth.sharad.com
    container_name: ministryofhealth.sharad.com
    networks:
      - mcdl

  aiimsindia.hospital.sharad.com:
    container_name: aiimsindia.hospital.sharad.com
    extends:
      file:  base/docker-compose-base.yaml
      service: aiimsindia.hospital.sharad.com
    networks:
      - mcdl

  uhgusa.hospital.sharad.com:
    container_name: uhgusa.hospital.sharad.com
    extends:
      file:  base/docker-compose-base.yaml
      service: uhgusa.hospital.sharad.com
    networks:
      - mcdl

  sbi.insurancecompany.sharad.com:
    container_name: sbi.insurancecompany.sharad.com
    extends:
      file:  base/docker-compose-base.yaml
      service: sbi.insurancecompany.sharad.com
    networks:
      - mcdl

  uhg.insurancecompany.sharad.com:
    container_name: uhg.insurancecompany.sharad.com
    extends:
      file:  base/docker-compose-base.yaml
      service: uhg.insurancecompany.sharad.com
    networks:
      - mcdl

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - SYS_CHANNEL=$SYS_CHANNEL
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=aiimsindia.hospital.sharad.com
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.sharad.com/peers/aiimsindia.hospital.sharad.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.sharad.com/peers/aiimsindia.hospital.sharad.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.sharad.com/peers/aiimsindia.hospital.sharad.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/hospital.sharad.com/users/Admin@org1.sharad.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ministryofhealth.sharad.com
      - aiimsindia.hospital.sharad.com
      - uhgusa.hospital.sharad.com
      - sbi.insurancecompany.sharad.com
      - uhg.insurancecompany.sharad.com
    networks:
      - mcdl