# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

networks:
  mcdl:

services:
  ca0:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-hospital
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.hospital.sharad.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/6decc31ba5eab6cb81b99f13257b8575a49813bf932907a722106cddebb79b9f_sk
      - FABRIC_CA_SERVER_PORT=7054
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.hospital.sharad.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/6decc31ba5eab6cb81b99f13257b8575a49813bf932907a722106cddebb79b9f_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/hospital.sharad.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerHospital
    networks:
      - mcdl

  ca1:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-insurancecompany
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.insurancecompany.sharad.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/8d0af8f99ca257a624b9f71e2c8fa3b4635a34cd79a36830241b5d58cbbd68a8_sk
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.insurancecompany.sharad.com-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/8d0af8f99ca257a624b9f71e2c8fa3b4635a34cd79a36830241b5d58cbbd68a8_sk -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/insurancecompany.sharad.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerInsurancecompany
    networks:
      - mcdl